"""Ideation + manuscript scaffolding and assembly (Pillars 4 & 6).

Two ideas, one module: seed a project's *plan* into the store (ideation is
store-native — thesis/contributions are claims, risks are questions, the
evaluation design is a decision entry; never a planning markdown file, which
would be a second drifting copy of graph state), and scaffold its *manuscript*
(a LaTeX skeleton wired to the `\\spancite` macro). The manuscript never
restates results — ``weave`` regenerates ``results_table.tex`` from ``metric``
rows and ``references.bib`` from cited papers, so the numbers and the
bibliography are build outputs of the store, not hand-typed text that can drift.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from . import experiment
from .cite import LATEX_PREAMBLE
from .db import now, project_id
from .project import Project

GENERATED_BANNER = "% GENERATED by `reref weave` — do not edit; numbers come from the store.\n"

PAPER_TEMPLATE = r"""\documentclass{{article}}
\usepackage{{booktabs}}
\input{{preamble}}

\title{{{title}}}
\author{{}}
\date{{}}

\begin{{document}}
\maketitle

\begin{{abstract}}
% Every quantitative claim here must match a metric row (see results_table.tex).
\end{{abstract}}

\section{{Introduction}}
% Cite prior work with \spancite{{<source_id>}}{{<start>}}{{<end>}}{{<quote>}} —
% generate cites with `reref cite "<claim>" {slug}`.

\section{{Related Work}}

\section{{Method}}

\section{{Experiments}}
\input{{results_table}}   % GENERATED — `reref weave {slug}`

\section{{Results}}

\section{{Conclusion}}

\bibliographystyle{{plain}}
\bibliography{{references}}      % GENERATED — `reref weave {slug}`
\end{{document}}
"""


def scaffold_from_template(corpus_root, slug: str, title: str) -> list[Path]:
    """Instantiate a new project from the committed templates/project/ folder.

    Copies the template tree into projects/<slug>/, substituting {{slug}}/{{title}}/
    {{date}}, renaming ``gitignore`` → ``.gitignore``. Never clobbers existing files
    (idempotent). The \\spancite preamble is written from the engine so it stays in
    sync with the macro. Falls back to the programmatic scaffold if no template dir.
    """
    tmpl = Path(corpus_root) / "templates" / "project"
    dest = Path(corpus_root) / "projects" / slug
    sub = {"{{slug}}": slug, "{{title}}": title, "{{date}}": now()[:10]}

    if not tmpl.exists():
        proj = Project(dest)
        proj.ensure()
        (dest / "runs").mkdir(exist_ok=True)
        return scaffold_paper(dest, slug, title)

    written = []
    for src in sorted(tmpl.rglob("*")):
        parts = list(src.relative_to(tmpl).parts)
        if parts[-1] == "gitignore":
            parts[-1] = ".gitignore"
        target = dest.joinpath(*parts)
        if src.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            continue
        data = src.read_text(encoding="utf-8", errors="replace")
        for k, v in sub.items():
            data = data.replace(k, v)
        target.write_text(data)
        written.append(target)
    # engine-sourced preamble (kept in sync with the \spancite macro)
    (dest / "text").mkdir(parents=True, exist_ok=True)
    (dest / "text" / "preamble.tex").write_text(LATEX_PREAMBLE.lstrip("\n"))
    return written


# --- Pillar 4: ideation (store-native) ----------------------------------------
def seed_ideation(con: sqlite3.Connection, slug: str) -> dict | None:
    """Seed a NEW project's plan into the store: one open kickoff question.

    The plan lives in the graph, not in a file — thesis/contributions become
    claims, the evaluation design a decision entry, risks become questions,
    positioning is cited papers. Skipped if the project already has log entries
    (idempotent, and never pollutes an in-flight project).
    """
    from . import log as logmod
    pid = project_id(con, slug)
    if con.execute("SELECT 1 FROM log_entry WHERE project_id=? LIMIT 1", (pid,)).fetchone():
        return None
    return logmod.add_entry(
        con, slug, "question",
        "Ideation: what is the thesis, and what evidence would support it? "
        "State the thesis and contributions as claims, the evaluation design as "
        "a decision entry (designed before building), open risks as questions, "
        "and position against prior art by citing papers. The plan lives in this "
        "graph — not in a file.",
        source="scaffold")


# --- Pillar 6: manuscript scaffold -------------------------------------------
def scaffold_paper(project_root: Path, slug: str, title: str) -> list[Path]:
    """Write the text/ skeleton: paper.tex + preamble.tex (idempotent on paper.tex)."""
    proj = Project(project_root)
    proj.ensure()
    written = []
    preamble = proj.text / "preamble.tex"
    preamble.write_text(LATEX_PREAMBLE.lstrip("\n"))
    written.append(preamble)
    paper = proj.text / "paper.tex"
    if not paper.exists():
        paper.write_text(PAPER_TEMPLATE.format(title=title, slug=slug))
        written.append(paper)
    return written


# --- Pillar 6: assembly (numbers + bib are generated, never typed) -----------
def weave_results_table(con: sqlite3.Connection, project: str, project_root: Path) -> Path:
    """Regenerate results_table.tex from the latest metric rows of each experiment."""
    rows = experiment.list_experiments(con, project)
    cols = sorted({name for r in rows for name in (r["metrics"] or {})})
    out = Path(project_root) / "text" / "results_table.tex"
    out.parent.mkdir(parents=True, exist_ok=True)

    if not cols:
        out.write_text(GENERATED_BANNER +
                       "% No metrics yet — run an experiment, then `reref weave`.\n")
        return out

    def fmt(v):
        return f"{v:.3f}" if isinstance(v, float) else str(v)

    header = "Experiment & " + " & ".join(c.replace("_", r"\_") for c in cols) + r" \\"
    body = []
    for r in rows:
        m = r["metrics"] or {}
        if not m:
            continue
        cells = [fmt(m[c]) if c in m else "--" for c in cols]
        body.append(r["slug"].replace("_", r"\_") + " & " + " & ".join(cells) + r" \\")

    table = (
        GENERATED_BANNER
        + "\\begin{table}[h]\\centering\n\\begin{tabular}{l" + "c" * len(cols) + "}\n"
        + "\\toprule\n" + header + "\n\\midrule\n"
        + "\n".join(body) + "\n\\bottomrule\n\\end{tabular}\n"
        + "\\caption{Results (generated from recorded runs).}\n\\end{table}\n"
    )
    out.write_text(table)
    return out


def weave_bib(con: sqlite3.Connection, project: str, project_root: Path) -> Path:
    """Regenerate references.bib from the paper table, falling back to citation source ids.

    Real bibliographic entries come from the `paper` table (Pillar 1). Until papers
    are ingested, we emit resolvable @misc stubs for each source id cited in the
    project's citations.json so \\bibliography still compiles.
    """
    out = Path(project_root) / "text" / "references.bib"
    out.parent.mkdir(parents=True, exist_ok=True)
    entries: dict[str, str] = {}

    papers = con.execute("SELECT * FROM paper ORDER BY key").fetchall()
    for p in papers:
        authors = " and ".join(json.loads(p["authors_json"] or "[]")) or "Unknown"
        entries[p["key"]] = (
            f"@article{{{p['key']},\n  title = {{{p['title'] or ''}}},\n"
            f"  author = {{{authors}}},\n  year = {{{p['year'] or ''}}},\n"
            f"  doi = {{{p['doi'] or ''}}}\n}}\n"
        )

    from . import ingest
    for cit in ingest.citations_for_project(con, project):
        sid = cit["source_id"]
        if sid and sid not in entries:
            entries[sid] = (
                f"@misc{{{sid},\n  title = {{{sid}}},\n"
                f"  note = {{stub — ingest the paper (Pillar 1) for full metadata}}\n}}\n"
            )

    out.write_text("% GENERATED by `reref weave` — edit the paper/citation store, not here.\n\n"
                   + "\n".join(entries[k] for k in sorted(entries)))
    return out


def weave(con: sqlite3.Connection, project: str, project_root: Path) -> list[Path]:
    from . import ingest
    project_id(con, project)  # validate the project exists
    return [weave_results_table(con, project, project_root),
            weave_bib(con, project, project_root),
            ingest.regenerate_sidecar(con, project, project_root)]
