// Folder tree used by Write and the Instructions / Templates admin pages.
// Same chrome language as the manuscript `text/` pane: chevrons, indent,
// optional tag (weave, …). `path` is the identity; `name` is the leaf label.
import React, { useState } from 'react'

function dirsOf(nodes, acc = []) {
  for (const n of nodes || []) {
    if (n.kind === 'dir') { acc.push(n.path); dirsOf(n.children, acc) }
  }
  return acc
}

function TreeNode({ node, depth, open, toggle, active, onOpen }) {
  if (node.kind === 'dir') {
    const shown = open.has(node.path)
    return (
      <div>
        <button className="tx-fn tx-dir" style={{ '--d': depth }}
                onClick={() => toggle(node.path)}>
          <span className="tx-chev">{shown ? '▾' : '▸'}</span>
          <span className="tx-fn-name">{node.name}</span>
        </button>
        {shown && (node.children || []).filter((c) => !c.build).map((c) => (
          <TreeNode key={c.path} node={c} depth={depth + 1} open={open}
                    toggle={toggle} active={active} onOpen={onOpen} />
        ))}
      </div>
    )
  }
  const tag = node.tag || (node.generated ? 'weave' : null)
  return (
    <button
      className={`tx-fn ${active === node.path ? 'on' : ''} ${node.generated ? 'gen' : ''}`}
      style={{ '--d': depth }}
      onClick={() => onOpen(node)}
      title={node.title || (node.generated ? 'generated by renv weave — not editable' : node.path)}
    >
      <span className="tx-chev" />
      <span className="tx-fn-name">{node.name}</span>
      {tag && <span className="tx-tag">{tag}</span>}
    </button>
  )
}

export function FileTree({ tree, active, onOpen }) {
  const [open, setOpen] = useState(() => new Set(['', ...dirsOf(tree)]))
  const toggle = (path) => {
    setOpen((s) => {
      const n = new Set(s)
      if (n.has(path)) n.delete(path); else n.add(path)
      return n
    })
  }
  return (
    <div className="tx-tree">
      {(tree || []).map((n) => (
        <TreeNode key={n.path} node={n} depth={0} open={open} toggle={toggle}
                  active={active} onOpen={onOpen} />
      ))}
    </div>
  )
}

// Nested dir/file tree from a flat list of `{ path, ... }` rows. `strip` is an
// optional prefix dropped from the visible tree (chrome already names it).
export function filesToTree(files, { strip = '' } = {}) {
  const pre = (strip || '').replace(/\/$/, '')
  const rel = (p) => {
    if (pre && p.startsWith(pre + '/')) return p.slice(pre.length + 1)
    return p
  }
  const root = []
  const dirs = new Map()
  const ensureDir = (full) => {
    if (dirs.has(full)) return dirs.get(full)
    const parts = full.split('/').filter(Boolean)
    const name = parts[parts.length - 1]
    const parent = parts.slice(0, -1).join('/')
    const node = { kind: 'dir', path: (pre ? `${pre}/${full}` : full), name, children: [] }
    dirs.set(full, node)
    if (!parent) root.push(node)
    else ensureDir(parent).children.push(node)
    return node
  }
  for (const f of files || []) {
    if (!f?.path) continue
    const shown = rel(f.path)
    const parts = shown.split('/').filter(Boolean)
    const name = parts.pop()
    const parent = parts.join('/')
    const node = {
      kind: 'file', path: f.path, name,
      file: f, generated: !!f.generated, tag: f.tag,
      title: f.description || f.path,
    }
    if (parent) ensureDir(parent).children.push(node)
    else root.push(node)
  }
  const sortNodes = (ns) => {
    ns.sort((a, b) => (a.kind !== b.kind ? (a.kind === 'dir' ? -1 : 1)
      : a.name.localeCompare(b.name)))
    ns.forEach((n) => n.children && sortNodes(n.children))
  }
  sortNodes(root)
  return root
}
