"""Phase E: automated per-section critique (Pillar 8)."""

from __future__ import annotations

from pathlib import Path

from renv.research import authoring, db, experiment, review


def _project_with_run(tmp_path, recall=0.80):
    con = db.connect(tmp_path)
    db.ensure_project(con, "p", title="P")
    root = tmp_path / "projects" / "p"
    (root / "text").mkdir(parents=True)
    experiment.create_experiment(con, "p", "001", hypothesis="dense helps")
    entry = tmp_path / "e.py"
    entry.write_text("import json,os\n"
                     f"json.dump({{'recall':{recall}}}, open(os.environ['RENV_RUN_DIR']+'/metrics.json','w'))\n")
    experiment.run_experiment(con, "p", "001", entrypoint=str(entry), root=str(tmp_path))
    authoring.weave(con, "p", root)
    return con, root


def _write_paper(root, abstract="", body=""):
    (root / "text" / "paper.tex").write_text(
        "\\begin{abstract}" + abstract + "\\end{abstract}\n"
        "\\input{results_table}\n" + body + "\n\\bibliography{references}\n")


def test_clean_paper_has_no_high_findings(tmp_path):
    con, root = _project_with_run(tmp_path, recall=0.80)
    _write_paper(root, abstract="We reach recall of 0.800 on the benchmark.")
    findings = review.run_automated(con, str(tmp_path), "p")
    highs = [f for f in findings if f["severity"] == "high"]
    assert not highs, highs


def test_fabricated_abstract_number_is_flagged(tmp_path):
    con, root = _project_with_run(tmp_path, recall=0.80)
    _write_paper(root, abstract="We improve recall to 0.990, a huge gain.")
    findings = review.run_automated(con, str(tmp_path), "p")
    ids = {f["check_id"] for f in findings}
    assert "abs-claims-match-metrics" in ids
    assert any("0.990" in f["issue"] for f in findings)


def test_abstract_number_requires_woven_table(tmp_path):
    """A metric in the DB is not enough — the number must appear in the table."""
    con, root = _project_with_run(tmp_path, recall=0.80)
    (root / "text" / "results_table.tex").write_text(
        "% GENERATED by `renv weave`\n% No metrics yet — run an experiment.\n")
    _write_paper(root, abstract="We reach recall of 0.800 on the benchmark.")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "abs-claims-match-metrics" and "0.800" in f["issue"]
               for f in findings)


def test_comment_only_table_is_stale(tmp_path):
    """A comment containing the metric string is not a cell and not freshness."""
    con, root = _project_with_run(tmp_path, recall=0.80)
    (root / "text" / "results_table.tex").write_text("% GENERATED\n% 0.800\n")
    _write_paper(root, abstract="We reach recall of 0.800 on the benchmark.")
    ids = {f["check_id"] for f in review.run_automated(con, str(tmp_path), "p")}
    assert "results-table-fresh" in ids
    assert "abs-claims-match-metrics" in ids


def test_table_trailing_comment_is_not_a_cell(tmp_path):
    con, root = _project_with_run(tmp_path, recall=0.80)
    table = root / "text" / "results_table.tex"
    table.write_text(table.read_text().replace("0.800", "0.800 % 0.990", 1))
    _write_paper(root, abstract="We reach accuracy 0.990.")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "abs-claims-match-metrics" and "0.990" in f["issue"]
               for f in findings)


def test_experiment_slug_is_not_a_table_cell(tmp_path):
    con, root = _project_with_run(tmp_path, recall=0.80)
    (root / "text" / "results_table.tex").write_text(
        "% GENERATED\n\\begin{tabular}{lc}\n"
        "sota-0.990 & 0.800 \\\\\n\\end{tabular}\n")
    _write_paper(root, abstract="We reach accuracy 0.990.")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "abs-claims-match-metrics" and "0.990" in f["issue"]
               for f in findings)


def test_input_sidecar_is_scanned(tmp_path):
    con, root = _project_with_run(tmp_path, recall=0.80)
    (root / "text" / "abs.tex").write_text("We reach accuracy 0.990.\\cite{invented}\n")
    (root / "text" / "paper.tex").write_text(
        "\\begin{abstract}\\input{abs}\\end{abstract}\n"
        "\\input{results_table}\n\\bibliography{references}\n")
    ids = {f["check_id"] for f in review.run_automated(con, str(tmp_path), "p")}
    assert "abs-claims-match-metrics" in ids
    assert "bib-known-paper" in ids


def test_unverified_spancite_is_flagged(tmp_path):
    con, root = _project_with_run(tmp_path)
    # a citation row where the cite only partially supports the claim
    class _Cit:
        source_id = "gao2023_alce"; claim = "q"; start, end = 100, 200
        quote = prefix = suffix = ""; support = "partial"; support_score = 0.5
    from renv.papers import ingest
    ingest.record_citation(con, "p", _Cit())
    _write_paper(root, body="A claim.\\spancite{gao2023_alce}{100}{200}{q}")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "cites-verify-full" and "partial" in f["issue"]
               for f in findings)


def test_missing_bib_entry_is_flagged(tmp_path):
    con, root = _project_with_run(tmp_path)
    (root / "text" / "references.bib").write_text("")  # empty bib
    _write_paper(root, body="See \\cite{smith2024}.")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "bib-coverage" and "smith2024" in f["issue"]
               for f in findings)
    assert any(f["check_id"] == "bib-known-paper" and "smith2024" in f["issue"]
               for f in findings)


def test_cite_key_without_paper_row_is_flagged(tmp_path):
    """A weave @misc stub satisfies bib-coverage but not bib-known-paper."""
    con, root = _project_with_run(tmp_path)
    (root / "text" / "references.bib").write_text("@misc{smith2024, title={x}}\n")
    _write_paper(root, body="See \\cite{smith2024}.")
    findings = review.run_automated(con, str(tmp_path), "p")
    ids = {f["check_id"] for f in findings if "smith2024" in f["issue"]}
    assert "bib-known-paper" in ids
    assert "bib-coverage" not in ids


def test_spancite_unknown_key_is_bib_known_paper(tmp_path):
    con, root = _project_with_run(tmp_path)
    _write_paper(root, body="A claim.\\spancite{nobody}{1}{2}{q}")
    findings = review.run_automated(con, str(tmp_path), "p")
    assert any(f["check_id"] == "bib-known-paper" and "nobody" in f["issue"]
               for f in findings)


def test_review_writes_report(tmp_path):
    con, root = _project_with_run(tmp_path)
    _write_paper(root, abstract="recall 0.800")
    res = review.review(con, str(tmp_path), "p")
    assert Path(res["report"]).exists()
    assert "# Review — p" in Path(res["report"]).read_text()
